queue_rules:
  - name: default
    merge_method: squash
    conditions:
      - check-success=test
pull_request_rules:
  - name: automatic approval for updatecli pull requests
    conditions:
      - check-success=test
      - files~=^(README.md|.mergify.yml|docs/versions.yml)$
      - head~=^updatecli_.*
    actions:
      review:
        type: APPROVE
        message: Automatically approving mergify
  - name: squash and merge updatecli PRs after CI passes
    conditions:
      - author=github-actions[bot]
      - check-success=test
      - files~=^(README.md|.mergify.yml|docs/versions.yml)$
      - head~=^updatecli_.*
      - -conflict
      - "#approved-reviews-by>=1"
    actions:
      queue:
        name: default
  - name: rebase pull requests
    conditions:
      - files~=^(README.md|.mergify.yml|docs/versions.yml)$
      - head~=^updatecli_.*
      - "#check-failure>0"
    actions:
      rebase: